version: '3.9'

services:
  postgres:
    image: postgres:latest    
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=desafio-somos-db
    volumes:
      - pgdata:/data/postgres    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-somos-docker
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    

volumes:
  pgdata:
    driver: local
